baseurl = "https://www.econometrics.ruhr/blog/"
title = "Dates & News"
canonifyurls = true
paginate = 10
theme = "startbootstrap-clean-blog"
languageCode = "en-us"
copyright = "The participating universities do not take any liability for the correctness and completeness of the information on their websites. The same applies to the contents of linked pages."
publishDir = "../docs/blog/"

[markup]
  defaultMarkdownHandler = "blackfriday"

[author]
  name = "Martin Arnold"

[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = ""
  Author = ""
  email = ""
  Ganalytics = "XX-00000000-0"
  imprint = '<a href="https://www.statistik.tu-dortmund.de/impressum0.html" target="_blank">Imprint</a>'
  prpolicy = '<a href="https://www.statistik.tu-dortmund.de/datenschutzerklaerung0.html" target="_blank">Privacy Policy</a>'
  # This will load all the CSS defined in the list
  # customCSS = ["<absolute path to CSS>", "/static/css/test.css", "<or just load it off the internet>"]

#[[params.social]]
#    title = "twitter"
#    url = ""
#[[params.social]]
#    title = "github"
#    url = ""
#[[params.social]]
#    title = "facebook"
#    url = ""

[[menu.main]]
  name = "Start"
  url = "/"
  weight = -200
[[menu.main]]
  name = "Archives"
  url = "/post/"
  weight = -180
